GITHUB_REPONAME = "Ramblurr/blog"
require 'rubygems'
require 'tmpdir'

version = ">= 0"
gem 'jekyll', version
load Gem.bin_path('jekyll', 'jekyll', version)


namespace :site do
  desc "Generate blog files"
  task :generate do
    Jekyll::Site.new(Jekyll.configuration({
      "source"      => ".",
      "destination" => "_site"
    })).process
  end


  desc "Generate and publish blog to gh-pages"
  task :publish => [:generate] do
    Dir.mktmpdir do |tmp|
      system "rsync -az --delete _site _site_gh"
      Dir.chdir "_site_gh"
      system "git add ."
      message = "Site updated at #{Time.now.utc}"
      system "git commit -m #{message.shellescape}"
      system "git push origin master:refs/heads/gh-pages"
    end
  end
end
